src/snake/mod.rs
=> HEY I FOUND A BUG

src/fighter/common/common_status/attack.rs
=> One final one. Please. For my own sake.

src/fighter/jack/acmd.rs, src/fighter/jack/agent_init.rs, src/fighter/jack/mod.rs, src/fighter/jack/status.rs
=> Reimplements Phantom Dash to a Status edit.

src/fighter/jack/status.rs
=> Now properly transitions to Idle

src/fighter/common/command_inputs.rs, src/fighter/common/common_param.rs, src/fighter/lucina/agent_init.rs
=> Yu command input fixes again

src/fighter/common/common_status/escape.rs, src/fighter/ken/status.rs, src/fighter/ryu/helper.rs, src/fighter/ryu/status.rs, src/function_hooks.rs
=> Params reimplementation

src/fighter/bayonetta/agent_init.rs, src/fighter/bayonetta/mod.rs, src/fighter/common/agent_inits.rs
=> Bayo can always cancel Fair into Side B

src/fighter/palutena/acmd.rs
Resolves #53 
Palutena update finished. Still got ZSS and Wii Fit to go on my end.
=> Palutena tilts

src/fighter/lucina/acmd/specials.rs, src/fighter/lucina/frame.rs, src/fighter/lucina/helper.rs, src/fighter/lucina/status.rs, src/function_hooks.rs
=> Shadow narukami buffs

src/fighter/common/common_status/attack_3.rs
Before, you had to pivot cancel to perform sliding f-tilts. Now, any f tilt will preserve momentum.
=> Sliding F-Tilts

WuBor-Utils/src/vars.rs, WuBor-Utils/src/wua_bind.rs, src/fighter/dolly/acmd/aerials.rs, src/fighter/dolly/acmd/normals.rs, src/fighter/dolly/acmd/specials.rs, src/fighter/dolly/frame.rs, src/fighter/dolly/helper.rs, src/fighter/lucario/acmd/specials.rs, src/fighter/lucina/acmd/specials.rs, src/fighter/ryu/frame.rs
Changelog
Stats
Super Meter
F.Tilt (No Angle)
F.Tilt (Low)
F.Air
U.Air
Rising Tackle
=> Terry (Again???) - 0.15.1

Cargo.toml, WuBor-Utils/src/vars.rs, src/fighter/common/common_status.rs, src/fighter/common/common_status/cliff.rs, src/fighter/common/common_status/sub_fighter.rs
Ledge Intangibility now goes away when you are no longer in the `FALL`, `FALL_AERIAL`, `JUMP_AERIAL`, or `FLY` states.
=> Ledge Intangibility Rework 2

src/fighter/common/status/escape_air.rs
Adds effects when you perform an air dash.
https://user-images.githubusercontent.com/26860994/210020628-7b987268-40cd-4678-bd8f-356c4ab71603.mp4
=> Added Effects to Air Dash

src/fighter/chrom/status.rs, src/fighter/common/status/attack.rs, src/fighter/common/status/attack_100.rs, src/fighter/common/status/attack_3.rs, src/fighter/common/status/attack_4.rs, src/fighter/common/status/escape_air_slide.rs, wubor-changelog/src/system/engine.md, wubor-changelog/src/system/mechanics.md
Increases Wave Land distance
Reduces Air Dash landing lag
Enables all normals to carry horizontal momentum
F Smash does not carry momentum if it's performed during dash.
=> Slip n Slide

wubor-changelog/src/stages.md, wubor-changelog/src/system/engine.md
=> Removes the Spike Blast Zone

.github/workflows/build_pr.yml, .github/workflows/build_release.yml, src/system.rs, src/system/engine.rs, wubor-changelog/src/system/engine.md
Adjusts the behavior of electric hitlag to be consistent with Melee.
Borrowed directly from HDR.
=> Electric Hitlag Adjustment

src/system.rs, src/system/css.rs
=> Preserve the Previously Selected Character

src/fighter/common/status/guard/guard_on.rs
Instead of delaying to the next frame, the Shield graphic now appears on frame 1.
Unless you're Yoshi. Then it hasn't changed.
=> Shield Appears on Frame 1

src/fighter/lucario/agent_init.rs, src/fighter/lucario/fgc.rs, src/fighter/lucario/mod.rs, src/fighter/rockman/acmd/normals.rs, src/fighter/rockman/fgc.rs, src/fighter/rockman/mod.rs
Reduced hitstop on Jabs.
Jab 3 is jump-cancelable on hit.
=> Mega Man Adjustments

src/fighter/common/status/attack/attack_4.rs, src/fighter/common/status/escape/escape_air_slide.rs, src/fighter/common/status/movement.rs, src/fighter/common/status/movement/run_brake.rs, src/fighter/common/status/movement/turn_run.rs, src/fighter/falco/status.rs, src/fighter/falco/status/attack.rs, src/fighter/falco/status/attack_s4.rs, src/fighter/fox/status.rs, src/fighter/fox/status/attack.rs, src/fighter/fox/status/attack_s4.rs, src/fighter/wolf/status.rs, src/fighter/wolf/status/attack.rs, src/fighter/wolf/status/attack_s4.rs
Lowers most characters tractions to allow for more sliding normals. Will feel like Smash 4 in terms of movement and that's good I like that game.
=> Slip n Slide - The Slidining

src/lib.rs
Fixes frame pacing issues on Ryujinx
=> Updated Emulator Offset Check

src/fighter/rockman/vtable_hook.rs
=> Enables charging Mega Buster during damaged states

WuBor-Utils/src/vars.rs, custom-var/src/lib.rs, src/fighter/common/status/guard/guard_damage.rs
Parry SFX now plays at 0.7x power on consecutive parries.
Consecutive parries no longer cause the screen to darken.
=> Parry FX Update

src/fighter/rockman/vtable_hook.rs
It would be cool but it bypasses an intentional design choice for the character.
=> Fix Side Taunt charging Mega Buster

WuBor-Utils/src/vars.rs, src/fighter/dolly/vtable_hook.rs, src/fighter/jack/vtable_hook.rs, src/fighter/lucina/frame.rs, src/fighter/lucina/helper.rs, src/fighter/lucina/vl.rs, src/fighter/lucina/vtable_hook.rs, src/system.rs
Overhauls the following characters' meter gain to not rely on commonly used hooks.
- Can now gain meter on hitting shield at 0.1x the normal rate.
- SP Gain Penalty timer shortened from 360 frames to 180 frames.
=> Small Meter Overhaul

src/fighter/dolly/acmd/aerials.rs, src/fighter/dolly/acmd/appeal.rs, src/fighter/dolly/acmd/normals.rs, src/fighter/dolly/acmd/smashes.rs
a suite of stupid changes from a chaotic individual, includes;
Uair FX touchups
Uair Hitbox and utility adjustments
Taunt hitboxes (we need more funny)
A dumb as hell upsmash and fsmash buff,
and introducing — tipper hammer punch
=> Gungle 0.00 a the terryring

src/fighter/snake/grenade.rs
Grenades now leave the ground when hit.
Grenades can no longeer be picked up.
=> Snake Adjustments

src/fighter/pikachu/status/special_hi.rs, src/fighter/pikachu/status/special_lw.rs, src/fighter/snake/acmd/specials.rs
Now share an aerial resource.
Extended hang time by 14 frames (66 > 80).
=> Small Adjustments

fighters/common/src/status/cliff.rs, fighters/common/src/status/cliff/cliff_wait.rs, src/system/engine.rs
When getting ledge trumped, your only options are to buffer ledge getup or ledge roll or let yourself get trumped.
=> Ledge Adjustments

Cargo.toml, src/lib.rs
substitutes building full motion_list.bin files with motion_patch.yaml files.
=> Runtime Motion Patching

fighters/common/src/status/catch/catch.rs
=> Increase Jostle on Dash Grab

fighters/common/src/status/guard/guard.rs, fighters/common/src/status/guard/guard_damage.rs, fighters/common/src/status/guard/guard_on.rs, fighters/common/src/status/guard/mod.rs
- Now has a hurtbox that is the roughly same size as the your shield, making it easier to grab shielding opponents.
https://github.com/user-attachments/assets/23948213-26c1-4416-98d0-155a9d356c56
=> Shield-Only Grab Hurtbox

fighters/lucina/src/helper.rs, src/system.rs
=> Disable Shadow Narukami (For Now)

fighters/mario/src/lib.rs, src/custom_vars.rs, src/system/controller.rs, src/system/engine.rs, src/system/one_frame.rs, src/vtable_hook/belmont_cross.rs, src/vtable_hook/blaster_bullet.rs, src/vtable_hook/dolly.rs, src/vtable_hook/dolly_burst.rs, src/vtable_hook/dolly_wave.rs, src/vtable_hook/edge_flare1.rs, src/vtable_hook/jack.rs, src/vtable_hook/koopa_breath.rs, src/vtable_hook/lucina.rs, src/vtable_hook/packun_poisonbreath.rs, src/vtable_hook/ryu_shinkuhadoken.rs, src/vtable_hook/shotos.rs, src/vtable_hook/sonic.rs, src/vtable_hook/weapon.rs
=> 13.0.4 Support

fighters/common/src/status/movement.rs, fighters/common/src/status/movement/squat.rs
=> Dash Back out of Crouch

fighters/common/src/status/cliff/cliff_wait.rs
Before, transitioning from Ledge Grab (CLIFF_CATCH) to Ledge Idle (CLIFF_WAIT) cleared the ledge trump flag.
Now it no longer clears that flag, making it more lenient to ledge trump an opponent during a ledge getup action.
This change does not affect tethers.
=> Ledge Hog Buffs
