- src/fighter/common/agent_inits.rs
- src/fighter/dolly/acmd/ground_normals.rs
- src/fighter/dolly/agent_init.rs
- src/fighter/dolly/helper.rs
- src/fighter/dolly/mod.rs
- src/fighter/dolly/status.rs
Resolves #37
- Reimplements ATTACK, ATTACK_DASH, ATTACK_S3, ATTACK_HI3
- Moved all non-status scripts to helper.rs
- Allowed Dash Attack to be input using Half Circle Forward + Attack/Special
- Restricted Dash Attack from transitioning into Super Specials
- Dash Attack is Light Power Charge, Input is Heavy Power Charge
> Power Charge Changes

- WuBor-Utils/src/vars.rs
- src/fighter/marth/acmd/stance_specials.rs
- src/fighter/marth/status/stance_specials.rs
Changelog:
Noble Side Special 1 - Close Call
Noble Side Special 2 - Flashing Blade
Noble Up Special - Divine Fang
> Marth - 0.15.1

- src/fighter/common/common_status/damage_fall.rs
- src/fighter/common/common_status/escape.rs
- src/fighter/common/common_status/escape_air.rs
- src/fighter/common/common_status/passive.rs
In 0.15.0 I experimented with changing the tech input, modeling how it works based on how other games handle teching out of hitstun. However, while I *did* like it as a concept, this doesn't actually... work for Smash. So this reverts the tech input changes to vanilla (you need to press shield), and increases the window to tech from 12 to 20, like in the older Smash games.
In addition, this fixes an inconsistency when trying to tech from tumble, where sometimes you would airdodge and land and other times you would airdodge and tech. Now it *should* tech more consistently.
> Revert Tech Input Changes + Increase Tech Window

- src/fighter/common/common_param.rs
- src/fighter/common/common_status/damage.rs
- src/fighter/lucina/acmd/specials.rs
Before, Balloon Knockback (known as Damage Speed-Up internally) used Hitstun Frames (reaction_frame) to determine if knockback is adjusted. Now, it's based on your knockback speed.
Changelog:
Subject to change.
> Balloon KB is now based on KB Speed

- WuBor-Utils/src/vars.rs
- src/fighter/common/common_status/damage_fall.rs
- src/fighter/pikmin/acmd/normals.rs
- src/fighter/pikmin/mod.rs
- src/fighter/pikmin/status.rs
- src/fighter/pikmin/status/attack_hi3.rs
- src/fighter/pikmin/status/attack_s3.rs
- src/fighter/pikmin/status/landing.rs
Mostly for the sake of fun, here are some Olimar changes.
Changelog:
Jab 1
Dash Attack
F.Tilt
U.Tilt
D.Tilt
> Olimar Changes

- src/fighter/ganon/acmd/aerials.rs
- src/fighter/marth/acmd/stance_specials.rs
- src/fighter/marth/status/stance_specials.rs
> Various Small Adjustments

- Cargo.toml
- src/fighter/common/param.rs
- src/fighter/common/status/passive.rs
0.15.1 introduced "Bad Techs" where you would have a slower tech animation and no intangibility if you teched while above weight + 33 %. This removes that, making all hits normally techable, save for intentionally untechable moves.
> Removes "Bad Techs" when teching while Corkscrewing

- src/fighter/common/frame.rs
- src/fighter/common/param.rs
- src/fighter/common/status/jump.rs
- src/fighter/common/status/jump_squat.rs
- src/system.rs
- src/system/get_param.rs
Changelog
Super Jumping:
Now uses a param hook to increase jump height.
Super Jump height is now 1.4x your Full Hop height.
Increased gravity during Super Jumps was removed.
Now functions properly when your stats have changed, like with the Bunny Hood or with Monado Jump active.
> Jumping Adjustments

- src/fighter/common/status/jump.rs
- src/system/get_param.rs
This was going to be a part of the previous Jump Adjustments PR but I couldn't get it to work in time.
This removes Ultimate's feature that increases your upwards speed on full hops.
> Removes Accelerated Full Hops

- WuBor-Utils/src/vars.rs
- WuBor-Utils/src/wua_bind.rs
- custom-cancel/src/lib.rs
- src/fighter/common/status.rs
- src/fighter/common/status/escape.rs
- src/fighter/common/status/escape_air.rs
- src/fighter/common/status/escape_air_slide.rs
- src/fighter/common/status/landing.rs
- src/fighter/common/status/sub_set_status.rs
- src/fighter/common/status/sub_transitions.rs
- src/fighter/edge/status/helper.rs
- src/fighter/lucario/status.rs
- src/fighter/lucario/status/escape_air_slide.rs
Directional Air Dodge actually has its own status that goes unused in vanilla, so here I am now making use of it.
Changelog:
- Makes Air Dash its own Status.
- This means that Air Dash is now exempt from Dodge Staling, so Air Dashing will no longer affect your normal dodges.
- That's it actually.
> Make Air Dash its own Status

- src/fighter/common/param.rs
- wubor-changelog/src/system/engine.md
Raises lower knockback speed threshold from 3.0 to 3.5
Lowered maximum balloon knockback's magnitude from 6 to 4
> Raises when Balloon Knockback starts taking into effect

- WuBor-Utils/src/table_const.rs
- WuBor-Utils/src/vars.rs
- src/fighter/common/param.rs
- src/fighter/common/status/dash.rs
- src/fighter/common/status/guard.rs
- src/fighter/common/status/guard_off.rs
- src/fighter/common/status/jump_squat.rs
- src/fighter/common/status/sub_transitions.rs
- wubor-changelog/src/system/engine.md
Completely overhauls Shielding to be more of a punishment for not Parrying/Dodging.
Changelog:
- Removes traditional Out of Shield. Attempting to perform an action that isn't Roll, Spotdodge, will forcefully drop your shield first, then buffer the input.
- Grabs will not force Shield Drop first if they are performed during the first few frames of putting up Shield.
- Removed the old custom shield release attack cancel implementation.
- Shield Release frames: 11 > 5
- Shield Release Disable Shield Frames: 0 > 6
- This value gets added to Shield Release frames to get the total amount of frames you cannot Shield at all after starting a Shield Release. For example, if you release Shield and Dash on the first possible frame (frame 6), Shield will *stay disabled* for another 6 frames.
> Complete Shield Rework

- src/fighter/rockman/acmd/aerials.rs
- src/fighter/rockman/vtable_hook.rs
- wubor-changelog/src/characters/smash4/rockman.md
Fixes a bug where Metal Blade wouldn't despawn if Mega Man gets hit before throwing it.
Cuts Air Shooter's blockstun in half.
> Mega Man Hotfixes

- src/fighter/common/status/damage.rs
- wubor-changelog/src/system/engine.md
While the DI Line was no doubt helpful to follow the opponent's trajectory, I always thought it was too small to see in normal gameplay to matter.
In addition, removing the DI line buffs defense a little bit, making DI something the opponent has to guess on again.
May not get merged.
> DI Line go Bye Bye

- custom-var/src/lib.rs
- src/fighter/common/status/guard/guard_damage.rs
- src/fighter/common/status/guard/guard_on.rs
- wubor-changelog/src/system/engine.md
* Fixed a bug where if shielding a multihit move, the shield graphic would no longer reflect the current remaining shield health.
* The Parry window is increased to 6 frames if Shield is held during a Parry.
* Parries can only be buffered if the Shield button was pressed for less than 5 frames, otherwise you will shield normally.
* This ***does not*** apply if Shield is held during a parry.
> Parry Updates

- WuBor-Utils/Cargo.toml
- WuBor-Utils/src/controls.rs
- WuBor-Utils/src/lib.rs
- src/fighter/common/energy/control.rs
- src/fighter/common/mod.rs
- src/fighter/common/status.rs
- src/fighter/common/status/movement/jump.rs
- src/fighter/common/status/sub.rs
- src/system.rs
- src/system/controller.rs
- src/system/modules.rs
- src/system/modules/control.rs
All of this code comes from HDR, with some modifications.
* Removes C-Stick drift.
* Horizontal Jump momentum no longer takes the C-Stick into account.
* The C-Stick lockout on Tilt/Special Stick is removed.
* C-Stick Aerials should no longer use the left stick's position in most scenarios.
* The C-Stick is no longer capable of performing fast falls.
* This includes Smash Stick, as well as cases where if you hold down on the left stick and tap upwards on the C-Stick.
* This comes with the trade off of being unable to fast fall while the C-Stick's stick override is active.
* Fixes Digital GCC Triggers
> Massive C Stick Overhaul + Others

- src/system/modules/control.rs
C Stick Aerials no longer turn into C Stick Nairs when hold-buffering from an aerial action.
> Fixes Hold-Buffered C Stick Aerials from Air Actions

- src/fighter/common/param.rs
- src/fighter/common/status/passive.rs
Instead of being forced into the spinning KB animation when you take a certain amount of damage, it now applies when you get launched with 45 frames of hitstun or more.
> Spinning KB Animation Repurposing

- src/fighter/elight/acmd/escape.rs
- src/fighter/elight/status.rs
- src/fighter/elight/status/escape.rs
In vanilla, Mythra's Spotdodge and Rolls have motion rates in them, probably to forcefully give them more endlag to compensate for Foresight.
In addition, Mythra was the only character who couldn't Spotdodge Cancel Roll.
This makes her spotdodge and rolls function like every other characters', which is technically a huge buff but I'll cross that bridge when I get to Aegis Changes 2 Electric Boogaloo.
> Mythra Dodge Fixes

- src/fighter/common/status/sub_fighter.rs
Previously, we removed fast falling getting canceled when performing Aerials and Specials. Now fast fall gets canceled when performing Specials.
> Specials end Fast Fall

- WuBor-Utils/src/vars.rs
- WuBor-Utils/src/wua_bind.rs
- src/fighter/lucina/acmd/specials.rs
- src/fighter/lucina/agent_init.rs
- src/fighter/lucina/cancel.rs
- src/fighter/lucina/mod.rs
- src/fighter/lucina/status/attack_dash.rs
- src/fighter/lucina/status/special_hi.rs
- src/fighter/lucina/status/special_lw.rs
- src/fighter/lucina/status/special_n.rs
- src/fighter/lucina/status/special_n_loop.rs
- src/fighter/lucina/status/special_s.rs
- src/fighter/lucina/status/special_s4.rs
- src/fighter/lucina/vtable_hook.rs
Narukami didn't quite survive on the transition to SMASHLINE2, so we've revived him from the dead using dark arts.
Fixes his inability to use command inputs, as well as refactors his command inputs to use unique statuses, relying less on persistent variables to handle if the command input version was used.
> Restores Narukami Back to Normal

- WuBor-Utils/src/vars.rs
- src/fighter/bayonetta/status/attack_air.rs
- src/fighter/common/status/attack/attack_air.rs
- src/fighter/trail/status/landing_attack_air.rs
- Aerial Shieldstun Multiplier increased (0.33 > 0.75)
- All characters' landing lag increased by 4
Damage to Shieldstun comparison:
```
Damage | Vanilla | WuBor
0 |       2 | 2
1 |       2 | 2
2 |       2 | 3
3 |       2 | 3
4 |       3 | 4
5 |       3 | 5
6 |       3 | 5
7 |       3 | 6
8 |       4 | 6
9 |       4 | 7
10 |       4 | 8
11 |       4 | 8
12 |       5 | 9
13 |       5 | 9
14 |       5 | 10
15 |       5 | 11
16 |       6 | 11
17 |       6 | 12
18 |       6 | 12
19 |       7 | 13
20 |       7 | 14
```
> Aerials Overhaul

- WuBor-Utils/src/vars.rs
- src/fighter/common/status/movement/dash.rs
- src/fighter/common/status/movement/turn.rs
- Removed the ability to dash back directly from Dash and Turn Dash. Instead, any valid "turn" input will put you into the standing turnaround state.
- Pivots can now transition into Turn Dash after one frame, like in previous games. This means Perfect Pivoting is truly back.
- To prevent accidentally performing a pivot when attempting to perform a dash back during Dash or Turn Dash, the flick window for a successful dash input is extended by two frames (2 > 4).
- Lowered the tap input buffer (7 > 5). If you've played HDR, you know how this feels.
> Dash and Pivot Adjustments

- WuBor-Utils/src/vars.rs
- src/fighter/kirby/status/lucario.rs
- src/fighter/lucario/acmd/normals.rs
- src/fighter/lucario/acmd/specials.rs
- src/fighter/lucario/auraball/acmd/specials.rs
- src/fighter/lucario/status/special_n.rs
- src/fighter/lucario/status/special_s.rs
Reverted to Smash 4 hitboxes and framedata
Aura Sphere logic adjusted (Kirby now matches Lucario).
Normal Aura Sphere adjusted:
- Life reduced (60 > 48)
- Speed reduced (2.5 > 2)
Now always performs the dashing grab variant.
The EX Throw check is now attached to the beginning of the move.
Momentum is now retained in the air when the grab ends.
Distance traveled reduced.
Distance gained from aura reduced.
> Lucario Adjustments

- src/fighter/dolly/acmd/normals.rs
- src/fighter/dolly/acmd/specials.rs
Initial lower hitbox can now hit aerial opponents.
Launcher ending hitbox now hits grounded opponents.
Removed extra air-only hitbox.
What was I cooking? I don't even know...
Increased the hitbox activity of the rising portion by 3 frames.
> Terry Adjustments

- src/fighter/common/status/guard/guard.rs
- src/fighter/common/status/guard/guard_damage.rs
Removes the 3 extra frames of advantage on Parry. The advantage is now the intangibility granted on parry.
Removes shield SDI.
Removes the buffer extension on Parry. This doesn't matter due to an earlier change made that fully buffers actions during hitstop.
> Shield Adjustments

- src/fighter/ken/acmd/aerials.rs
- src/fighter/ken/acmd/normals.rs
- src/fighter/ken/acmd/smashes.rs
- src/fighter/ryu/acmd/normals.rs
- src/fighter/ryu/acmd/smashes.rs
- src/fighter/ryu/acmd/specials.rs
- src/fighter/ryu/status/special_s_loop.rs
General hitstop reduction on normals and smash attacks.
Minor damage buffs.
- Reduced SDI multiplier (2.5 > 1.0).
- Normalized knockback across all hitboxes (more consistent confirms when spaced).
- Adjusted the air version so Ryu carries his momentum further.
General hitstop and damage reduction on normals and smash attacks.
- Reduced SDI multiplier (2.5 > 1.0).
- Normalized knockback across all hitboxes (more consistent confirms when spaced).
> Shotos Adjustments

- src/fighter/common/status/cliff.rs
Flips the logic for Ledge Trumping so that instead of the first player to grab ledge being forced off, any player after the first to grab the ledge gets forced off instead.
Players can still buffer ledge options to avoid getting trumped.
> Ledge Trump Logic Reversal

- fighters/common/src/effect.rs
- fighters/common/src/lib.rs
Removes the effect that occurs when a character fully charges a store-able special move.
This effect overlaps with the invincibility/intangibility flashing effect.
> Remove Max Charge Flashing

- WuBor-Utils/src/app.rs
- WuBor-Utils/src/vars.rs
- WuBor-Utils/src/wua_bind.rs
- fighters/dolly/src/acmd/normals.rs
- fighters/dolly/src/agent_init.rs
- fighters/dolly/src/frame.rs
- fighters/dolly/src/helper.rs
- fighters/dolly/src/status/attack_dash.rs
- fighters/dolly/src/status/special_hi.rs
- fighters/dolly/src/status/special_n.rs
- fighters/dolly/src/status/superspecial.rs
- fighters/ken/src/agent_init.rs
- fighters/ken/src/status.rs
- fighters/ken/src/status/attack_command1.rs
- fighters/ken/src/status/special_n2.rs
- fighters/kirby/src/agent_init.rs
- fighters/kirby/src/lib.rs
- fighters/kirby/src/status.rs
- fighters/kirby/src/status/dolly.rs
- fighters/kirby/src/status/ryu.rs
- fighters/kirby/src/status/ryu/special_n2.rs
- fighters/ryu/src/agent_init.rs
- fighters/ryu/src/status/guard.rs
- fighters/ryu/src/status/guard_on.rs
- fighters/ryu/src/status/special_n2.rs
- src/vtable_hook/dolly.rs
- src/vtable_hook/shotos.rs
- Cleaned up the custom command input shenanigans
Groundwork done to give him Hashogeki in the future. Due to limitations, we can't give it to him quite yet, so for now he gets to have Denjin Hadoken on command.
Command Inputs have been updated to be similar to SF6:
```
Hadoken: 236B > 236A
Hashogeki: 41236B > 214A
Tatsumaki Senpukyaku: 214B (unchanged)
Shoryuken: 623B > 623A
```
Removed the ability to b reverse it due to the input being changed.
Command Inputs have been updated to be similar to SF6:
```
Hadoken: 236B > 236A
Tatsumaki Senpukyaku: 214B (unchanged)
Shoryuken: 623B > 623A
Jinrai Kicks: 41236B (Ground) > 236B (Ground Only)
Dragonlash Kick: 41236(Air/During Quick Dash) > 623B (can now be used normally on the ground)
```
Command Inputs have been updated to be similar to …
> Command Input Shenanigans

- src/system/modules/control.rs
🦀🦀🦀🦀Hold Buffer is Back 🦀🦀🦀🦀
(Kinda)
Hold Buffer is reimplemented into the game.
Any input that can be hold buffered is only hold buffer-able for 24 frames.
Spotdodge and Roll are only hold buffered if both Shield and the left stick are held, instead of just Shield.
> Buffer Adjustments

- fighters/common/src/status/guard/guard_on.rs
- src/system/engine.rs
- Parrying requires fresh inputs every time (it will not automatically parry multihits by holding Shield after the first parry).
- Hitlag is now static, regardless of the strength of the move parried.
- If the attack parried was a direct attack: 18 frames
- If the attack parried was an indirect attack: 7 frames
> Parry Adjustments

- fighters/common/src/status/damage/damage_fly.rs
- fighters/common/src/status/passive.rs
The spinning knockback animation is now used when knockback speed exceeds 6.0.
Adjusts knockback aura effect to only show up when knockback speed exceeds 6.0.
Adjusts knockback aura effect size to be 0.65x the size.
Adjusts KB smoke to be 0.8x the size and have 0.6x opacity.
> Knockback Visual Adjustments

- fighters/mario/src/acmd.rs
- fighters/mario/src/acmd/aerials.rs
- fighters/mario/src/acmd/appeal.rs
- fighters/mario/src/acmd/smashes.rs
Allows Mario to use the fabled bonker. Press up taunt to swap Mario's hammer to the bonker. Doesn't have an effect or anything when you swap, but oh you'll know...
> Bonker Time

- fighters/common/src/energy/control.rs
We previously used the unused jump_speed_x_max param to cap jump speedi. Instead, we now use a built-in formula when air speed is calculated.
Shouldn't feel too different for most characters.
> Jump Speed Small Refactor

- fighters/brave/src/acmd/specials.rs
- fighters/buddy/src/acmd/specials.rs
- fighters/dedede/src/acmd/specials.rs
- fighters/duckhunt/src/acmd/specials.rs
- fighters/inkling/src/acmd.rs
- fighters/inkling/src/acmd/specials.rs
- fighters/koopajr/src/acmd/specials.rs
- fighters/murabito/src/status.rs
- fighters/packun/src/acmd/specials.rs
- fighters/pit/src/acmd/specials.rs
- fighters/reflet/src/acmd/specials.rs
- fighters/rosetta/src/acmd/specials.rs
- fighters/shizue/src/status.rs
- fighters/snake/src/acmd/specials.rs
- fighters/yoshi/src/acmd/specials.rs
In 0.17.0, recoveries were made universally like Melee, where you could only snap to the ledge while going downwards. In 0.17.1, some more linear recoveries had this change reverted due to the late addition of reverse Ledge Trump. Here, we're bringing more characters in-line with the changes made in 0.17.1:
- Characters with linear recoveries
- Characters with no hitbox on their recoveries
- Woosh: Unchanged
- Swoosh: Can now snap to ledge on frame 40 while going up.
- Kaswoosh: Can now snap to ledge on frame 50 while going up.
- Super Dedede Jump: Can now snap to ledge on frame 5 while going upwards on both sides.
- Duck Jump: Can now snap to ledge on frame 39 during the move's free movement (the same frame you can cancel the move).
- Super Jump: Can now snap to ledge on frame 20 after …
> Small Recovery Reversions

- fighters/common/src/status/cliff/cliff_wait.rs
- src/system/engine.rs
- Removed the ledge grab limit on normal ledge grabs. Tethers still can only grab the ledge 3 times.
- Ledge Trump *always* forces you off of the ledge and no longer allows you to buffer ledge options.
- As a consequence, ledge actionability was increased from frame 11 to frame 12.
> Ledge Adjustments

- fighters/common/src/status/sub_fighter.rs
- Total Ledge Intangibility (should now be) always set to 42 frames (12 Ledge Grab + 30 Actionable).
- Ledge Regrab timer reduced (48 > 30).
- Ledge Intangibility now carries into aerials.
- Adjusted the logic for enabling momentum transfer. Shouldn't affect too much.
> I Was Bored at Riptide and made this PR

- src/system/engine.rs
Uses the character's actual Gravity and Fall Speed stats for vertical knockback.
> Un-Universalize Vertical KB

- fighters/dedede/src/acmd.rs
- fighters/dedede/src/acmd/aerials.rs
- fighters/dedede/src/acmd/landing.rs
- fighters/donkey/src/acmd.rs
- fighters/donkey/src/acmd/landing.rs
- fighters/koopa/src/acmd.rs
- fighters/koopa/src/acmd/aerials.rs
- fighters/koopa/src/acmd/landing.rs
- fighters/koopajr/src/acmd/aerials.rs
- fighters/krool/src/acmd.rs
- fighters/krool/src/acmd/aerials.rs
- fighters/krool/src/acmd/landing.rs
- fighters/plizardon/src/acmd.rs
- fighters/plizardon/src/acmd/landing.rs
- fighters/wario/src/acmd.rs
- fighters/wario/src/acmd/aerials.rs
Removes screen shake from the following:
- Heavy Landing for Heavies
- All aerials *except* for stall-and-fall down airs.
> Landing Shake Removal

- WuBor-Utils/src/vars.rs
- fighters/common/src/energy/control.rs
- fighters/mario/src/acmd/specials.rs
- fighters/mario/src/agent_init.rs
- fighters/mario/src/frame.rs
- fighters/mario/src/status.rs
- fighters/mario/src/status/special_air_lw.rs
- fighters/mario/src/status/special_air_lw_cancel.rs
- fighters/mario/src/status/special_air_lw_fall.rs
- fighters/mario/src/status/special_air_lw_landing.rs
- fighters/mario/src/status/special_lw_jump.rs
- fighters/mario/src/status/special_lw_landing.rs
- fighters/mario/src/vl.rs
- Removes momentum transfer from the game. I felt that it didn't make enough of an impact to gamefeel to need to exist.
- Rewrote Long Jump and Down Special.
- Long Jump now functions closer to Super Mario 64, multiplying your momentum by 1.5x when performed unless performed at a standstill.
- Due to these changes, it is now possible to massively increase your speed while performing the BLJ.
- BLJ also has a funny speed-based hitbox if performed while going off of the stage.
> Disable Momentum Transfer + A Funny

- fighters/common/src/status/guard/guard_damage.rs
- src/system/energy/control.rs
- src/system/energy/damage.rs
- src/system/energy/mod.rs
Reworked Shield Pushback
- Getting pushed off of the stage/platform during shieldstun now puts you into the edge slip state.
- Friction is now standardized during shield pushback (0.06).
- Shield pushback used to be based on shield stun frames (Shield Stun * 0.09).
- Now it is based on the move's base damage dealt (Damage * 0.05 + 0.5). The maximum speed while being pushed back is also increased (1.3 > 2.5).
https://github.com/user-attachments/assets/7c9e44d0-35e9-4ddd-9bc4-fabbcb1a0329
- Shield pushback is now *additive* if your current pushback matches the direction of your incoming shield pushback. If the incoming shield pushback is in the other direction, your current pushback will be completely overwritten.
- Upon blocking attacks that are a true blockstring, any incoming cumulative …
> Shield Pushback Adjustments

- WuBor-Utils/src/vars.rs
- fighters/mario/src/acmd/aerials.rs
- fighters/mario/src/acmd/specials.rs
- fighters/mario/src/frame.rs
- fighters/mario/src/status/attack_air.rs
- fighters/mario/src/status/special_lw_jump.rs
- Hitbox moved upwards 1.5u
- Hitbox ID 1 is now cleared on the final launcher hit.
- Final hit angle adjusted (40 > 60).
- All hits can now reverse hit.
- Final hit bounce height slightly increased.
- No longer bounces if currently fast falling.
- Hitboxes brought inwards.
- Reflect Box is now active until all hitboxes clear.
- Now has 1.25x air control.
> Mario Adjustments

- src/vtable_hook/shulk.rs
Fixes an issue causing the art wheel to not put Shulk into the wheel select state during certain actions.
> Shulk Arts Wheel Fix

- WuBor-Utils/src/vars.rs
- fighters/common/src/status/guard/guard_damage.rs
- Guard Cancel Attack and Guard Cancel Taunt can now only be performed if Shield is held.
> Fix Guard Cancel Buffer

- README.md
Force enables the hazards on Fountain of Dreams, Smashville, Town and City, and Hollow Bastion, even when playing with Hazards Off.
Castle Siege and Wily's Castle now has their hazards again when playing on Hazards Off.
Requires TNN's stage config plugin.
> Stage Config
